version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb1
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root
    # expose the ports for external connections NOTE: when connecting from another container on the same network use port 3306
    ports:
      - 3316:3306
  web:
    # force this continer to wait for the database to load.
    depends_on:
    - db
    image: tomcat:8.5
    # move the war build file from the local directory to the proper internal container directory 
    volumes:
      - ./target/demo.war:/usr/local/tomcat/webapps/demo.war
      # expose the internal port 8080 via the external port 8085
    ports: 
      - '8085:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb1
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root
